program Tc52NET;

uses
  Forms,
  MAIN in 'MAIN.PAS' {MainForm},
  BLOCK1 in 'BLOCK1.PAS' {Blockwin},
  TCGETDIR in 'TCGETDIR.PAS' {GetDirDlg},
  CodeView in 'CodeView.pas' {ViewCodeDialog},
  ADDSCODE in 'ADDSCODE.PAS' {addscodedlg},
  EDTCODE in 'EDTCODE.PAS' {edtcodedlg},
  ADDRCODE in 'ADDRCODE.PAS' {addrcodedlg},
  ADDTCODE in 'ADDTCODE.PAS' {addtcodedlg},
  EDSCODE in 'EDSCODE.PAS' {edscodedlg},
  EDRCODE in 'EDRCODE.PAS' {edrcodedlg},
  DELSCODE in 'DELSCODE.PAS' {delscodedlg},
  DELTCODE in 'DELTCODE.PAS' {deltcodedlg},
  DELRCODE in 'DELRCODE.PAS' {delrcodedlg},
  CODELEN in 'CODELEN.PAS' {codelendlg},
  TCOMMON in 'TCOMMON.PAS',
  EDCLASS in 'EDCLASS.PAS' {edclassdlg},
  EDHOUSE in 'EDHOUSE.PAS' {edhousedlg},
  PREFER in 'PREFER.PAS' {prefdlg},
  GROUPSEL in 'GROUPSEL.PAS' {groupseldlg},
  CNFGYEAR in 'CNFGYEAR.PAS' {ConfigYeardlg},
  CNFGDAY in 'CNFGDAY.PAS' {configdaydlg},
  TTABLE in 'TTABLE.PAS' {Ttablewin},
  TCINFO in 'TCINFO.PAS' {InfoWin},
  SETBLOCK in 'SETBLOCK.PAS' {SetBlocksDlg},
  COPYBLCK in 'COPYBLCK.PAS' {CopyBlockDlg},
  MOVESUB in 'MOVESUB.PAS' {MoveSubDlg},
  SPLITSUB in 'SPLITSUB.PAS' {SplitSubDlg},
  SWAPSUB in 'SWAPSUB.PAS' {SwapSubDlg},
  AUTOALOC in 'AUTOALOC.PAS' {AutoAllocDlg},
  LINKSUB in 'LINKSUB.PAS' {LinkSubDlg},
  STCLASH in 'STCLASH.PAS' {StClashHelpDlg},
  ENTRY in 'ENTRY.PAS' {EntryDlg},
  MANCLASH in 'MANCLASH.PAS' {ManClashDlg},
  EXSUB in 'EXSUB.PAS' {ExcludeSubDlg},
  TTVERS in 'TTVERS.PAS' {VersionDlg},
  CNFGLEV in 'CNFGLEV.PAS' {ConfigureLevels},
  SWAPBLCK in 'SWAPBLCK.PAS' {ExchangeBlockDlg},
  MARGINS in 'MARGINS.PAS' {pmargins},
  TTGOTO in 'TTGOTO.PAS' {GotoDlg},
  TECLASH in 'TECLASH.PAS' {TeacherClashes},
  FNDRODLG in 'FNDRODLG.PAS' {findroomdlg},
  FNDSTDLG in 'FNDSTDLG.PAS' {findstudentdlg},
  FNDTEDLG in 'FNDTEDLG.PAS' {findteacherdlg},
  EDCUSTOM in 'EDCUSTOM.PAS' {EditCustomInfo},
  CHELP in 'CHELP.PAS' {ClashHelpDlg},
  TTPRNSEL in 'TTPRNSEL.PAS' {ttprintselectiondlg},
  TCLOAD in 'TCLOAD.PAS' {About},
  CLASHHLP in 'CLASHHLP.PAS' {ClashHelp},
  TFREEDLG in 'TFREEDLG.PAS' {Teachersfreedlg},
  TEFREE in 'TEFREE.PAS' {TeachersFree},
  ROFREE in 'ROFREE.PAS' {RoomsFree},
  RFREEDLG in 'RFREEDLG.PAS' {Roomsfreedlg},
  PROMODLG in 'PROMODLG.PAS' {promotestudentdlg},
  STUDLIST in 'STUDLIST.PAS' {StudentListWin},
  CREATE in 'CREATE.PAS' {CreateDlg},
  BCLSHDLG in 'BCLSHDLG.PAS' {blockclashesdlg},
  BLKCLASH in 'BLKCLASH.PAS' {BlockClashes},
  CLMATRIX in 'CLMATRIX.PAS' {cmatwin},
  CLMATSEL in 'CLMATSEL.PAS' {cmatsel},
  SUBBSDLG in 'SUBBSDLG.PAS' {SubjectBySubjectDlg},
  TETIMES in 'TETIMES.PAS' {TeacherTimes},
  TETIMDLG in 'TETIMDLG.PAS' {Teachertimesdlg},
  SUBTIMES in 'SUBTIMES.PAS' {SubjectTimes},
  SUTIMDLG in 'SUTIMDLG.PAS' {SubjectTimesdlg},
  GRPOFTE in 'GRPOFTE.PAS' {GroupofTeachers},
  GRPTEDLG in 'GRPTEDLG.PAS' {Groupofteachersdlg},
  ROOMTT in 'ROOMTT.PAS' {RoTtable},
  ROTTDLG in 'ROTTDLG.PAS' {RoomTTdlg},
  TEACHTT in 'TEACHTT.PAS' {TeTtable},
  TETTDLG in 'TETTDLG.PAS' {TeacherTTdlg},
  STUDTTAB in 'STUDTTAB.PAS' {STtable},
  STULIDLG in 'STULIDLG.PAS' {StudListDlg},
  STUTTDLG in 'STUTTDLG.PAS' {Studttabledlg},
  TCOMMON2 in 'TCOMMON2.PAS',
  BCKUPDLG in 'BCKUPDLG.PAS' {BackupDataDlg},
  FINDSTUD in 'FINDSTUD.PAS' {FindStudent},
  ROCLASH in 'ROCLASH.PAS' {RoomClashes},
  SUBJCTTT in 'SUBJCTTT.PAS' {SuTtable},
  SUBBYSLT in 'SUBBYSLT.PAS' {SubByTimeSlotWin},
  SUBBYSUB in 'SUBBYSUB.PAS' {SubBySubjectWin},
  SUBTTDLG in 'SUBTTDLG.PAS' {SubjectTTdlg},
  EDFAC2 in 'EDFAC2.PAS' {EditFac2},
  BROWSE in 'BROWSE.PAS' {BrowseDlg},
  ADDSTUD in 'ADDSTUD.PAS' {addstuddlg},
  DELSTUD in 'DELSTUD.PAS' {delstuddlg},
  DELYRSUB in 'DELYRSUB.PAS' {delyrsubdlg},
  REPYRSUB in 'REPYRSUB.PAS' {repysdlg},
  SUBYR in 'SUBYR.PAS' {Subyearwin},
  EDSTUD in 'EDSTUD.PAS' {edstuddlg},
  ALTER in 'ALTER.PAS' {AlterDlg},
  SEARCH in 'SEARCH.PAS' {SearchDlg},
  TTBCLASH in 'TTBCLASH.PAS' {ttclashDlg},
  BUILD in 'BUILD.PAS' {BuildDlg},
  BOXOP in 'BOXOP.PAS' {BoxDlg},
  SOLVE in 'SOLVE.PAS' {SolveDlg},
  STINPUT in 'STINPUT.PAS' {Stuinput},
  STINDLG in 'STINDLG.PAS' {studentinputdlg},
  TTSIZE in 'TTSIZE.PAS' {ttsizedlg},
  ADDCLASS in 'ADDCLASS.PAS' {AddclassDlg},
  DELCLASS in 'DELCLASS.PAS' {DelclassDlg},
  LENCLASS in 'LENCLASS.PAS' {lenClassDlg},
  showclas in 'showclas.pas' {ClassesShowDlg},
  sortgrp in 'sortgrp.pas' {SortGroupDlg},
  cfggrpmn in 'cfggrpmn.pas' {ConfigureGroupMenudlg},
  hints in 'hints.pas' {Hintsdlg},
  cnfgblck in 'cnfgblck.pas' {Configureblocks},
  tttoolbarwin in 'tttoolbarwin.pas' {TtableToolbarWin},
  blcktool in 'blcktool.pas' {blocktoolbarwin},
  gentool in 'gentool.pas' {gentoolbarwin},
  Stcommon in 'Stcommon.pas',
  segregat in 'segregat.pas' {SegregateDlg},
  STBARC in 'STBARC.PAS',
  ClassDefs in 'ClassDefs.pas',
  TimesWnd in 'TimesWnd.pas' {TimesWindow},
  PrintPreviewForm in 'PrintPreviewForm.pas' {PrntPreviewForm},
  SuWnd in 'SuWnd.pas' {SuWindow},
  TeWnd in 'TeWnd.pas' {TeWindow},
  RoWnd in 'RoWnd.pas' {RoWindow},
  RollClassWnd in 'RollClassWnd.pas' {RollClassWindow},
  FacWnd in 'FacWnd.pas' {FacultyWindow},
  HouseWnd in 'HouseWnd.pas' {HouseWindow},
  fixsub in 'fixsub.pas' {FixSubDlg},
  Preview in 'Preview.pas',
  rocldlg in 'rocldlg.pas' {roomClashdlg},
  DCPrijndael in 'DCPrijndael.pas',
  DCPsha1 in 'DCPsha1.pas',
  DCPsha256 in 'DCPsha256.pas',
  TeList in 'TeList.pas' {TeListWin},
  StBlockClash in 'StBlockClash.pas' {StClashWin},
  StudFree in 'StudFree.pas' {StudFreeWin},
  TeListSelect in 'TeListSelect.pas' {TeListSelDlg},
  tcommon5 in 'tcommon5.pas',
  LOGONDLG in 'LOGONDLG.PAS' {LoggingonDlg},
  ADDUSER in 'ADDUSER.PAS' {AddNewUserDlg},
  EDUSER in 'EDUSER.PAS' {EditUserDlg},
  EDPASSWD in 'EDPASSWD.PAS' {edpassworddlg},
  Deluser in 'Deluser.pas' {DeleteUserDlg},
  SHOWUSER in 'SHOWUSER.PAS' {ShowUsersWin},
  GTSPRPSS in 'GTSPRPSS.PAS' {getSuperPasswordDlg},
  Autoload in 'Autoload.pas' {autoloaddlg},
  CustomOutput in 'CustomOutput.pas',
  WebUpdate in 'WebUpdate.pas' {WebUpdateDlg},
  SubReportLen in 'SubReportLen.pas' {SubReportLendlg},
  InUse in 'InUse.pas' {SpecifyCurTtableDlg},
  EDitTIME in 'EDitTIME.PAS' {AllotDlg},
  TrackChoices in 'TrackChoices.pas' {TrackChoicesDlg},
  sbtsdlg in 'sbtsdlg.pas' {SubjectsByTimeSlotDlg},
  tecldlg in 'tecldlg.pas' {teacherclashdlg},
  DlgCommon in 'DlgCommon.pas',
  SubClassSize in 'SubClassSize.pas' {SetSubSizeDlg},
  TTundo in 'TTundo.pas',
  Tagdlg in 'Tagdlg.pas' {TagDialog},
  TimeChartGlobals in '..\Common\TimeChartGlobals.pas';

{$R *.RES}

begin
  Application.Title := 'Time Chart 2000';
  Application.HelpFile := 'TC52NET.HLP';
  Application.CreateForm(TMainForm, MainForm);
  Application.CreateForm(TGetDirDlg, GetDirDlg);
  Application.CreateForm(TAbout, About);
  Application.Run;
end.
